
# -----------------------------------------------------------------------------------------------------
# Site settings

title: The Work Of Maksim Shuster
email: maksim.shuster@gmail.com
description: > 
  UX, UI, Visual Design...and Identity and Branding and everything else that used to be called Graphic Design.
url: "http://maksimshuster.com" # the base hostname & protocol for your site
twitter_username: plusmasa
github_username:  plusmasa

#------------------------------------------------------------------------------------------------------